### ISSUE TITLE
Question about function `preprocess_negative`

### ISSUE THREAD

**Issue by Emperorizzis** [Reason-Wang/NAT#1]
Hi ~ Thanks for the open source firstly !

I have read your paper and codes roughly, integrating negative samples into the positive's is an excellent idea!

**But I haven't find any usage about function [`preprocess_negative`](https://github.com/Reason-Wang/NAT/blob/master/data/dataset.py#L117). Is there any problem or bug ?**

Looking forward to your reply.

**Comment by Reason-Wang** [comment]
Sorry for the confusion. This is a deprecated function which is not used. Now we use function `format_sample_with_prompt` to process positive and negative samples based on their `reward` or `f1`. We may delete this function later.

**Comment by Emperorizzis** [comment]
> Sorry for the confusion. This is a deprecated function which is not used. Now we use function `format_sample_with_prompt` to process positive and negative samples based on their `reward` or `f1`. We may delete this function later.

Thanks for you reply. ~
